import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI, Part } from "@google/generative-ai";

const GEMINI_MODEL = "gemini-2.0-flash";

const DOC_SYSTEM_PROMPT = `You are an expert technical documentation generator. Analyze screenshots of software workflows and generate clear, step-by-step documentation.

For each screenshot, return a JSON object with:
- step: number (sequential)
- title: string (max 60 chars, action-oriented like "Click the Settings button")
- description: string (max 200 chars, clear instructions)
- annotations: string[] (key UI elements visible)
- tip: string or null (practical troubleshooting hint)

Return a JSON array of these objects. No markdown, no explanation — only the JSON array.`;

async function generateWithGemini(
  images: Array<{ id: string; data: string; name: string }>
): Promise<
  Array<{
    step: number;
    title: string;
    description: string;
    imageUrl: string;
    annotations: string[];
    tip: string | null;
  }>
> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY not set");

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({ model: GEMINI_MODEL });

  const allSteps: Array<{
    step: number;
    title: string;
    description: string;
    imageUrl: string;
    annotations: string[];
    tip: string | null;
  }> = [];

  // Process one image at a time for clearest context
  for (let i = 0; i < images.length; i++) {
    const img = images[i];
    const base64Data = img.data.replace(/^data:image\/\w+;base64,/, "");

    const textPart: Part = {
      text: `${DOC_SYSTEM_PROMPT}\n\nThis is screenshot ${i + 1} of ${images.length} in a workflow sequence. Generate documentation for this step.`,
    };

    const imagePart: Part = {
      inlineData: {
        mimeType: "image/png",
        data: base64Data,
      },
    };

    // Retry with exponential backoff for rate limit errors
    let result;
    let attempts = 0;
    const maxAttempts = 3;

    while (attempts < maxAttempts) {
      try {
        result = await model.generateContent({
          contents: [{ role: "user", parts: [textPart, imagePart] }],
          generationConfig: {
            responseMimeType: "application/json",
            temperature: 0.2,
          },
        });
        break; // Success
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        attempts++;

        // Check if it's a rate limit (429) or quota error
        const isRateLimit = errorMessage.includes("429") || errorMessage.includes("Too Many Requests") || errorMessage.includes("quota");

        if (!isRateLimit || attempts >= maxAttempts) {
          throw err; // Rethrow non-rate-limit errors or after max retries
        }

        // Exponential backoff: 1s, 2s
        await new Promise((r) => setTimeout(r, attempts * 1000));
      }
    }

    const responseText = result!.response.text().trim().replace(/^```json\s*/i, "").replace(/\s*```$/i, "");

    if (responseText) {
      try {
        const parsed = JSON.parse(responseText);
        const steps = Array.isArray(parsed) ? parsed : [parsed];
        for (const s of steps) {
          allSteps.push({
            step: s.step ?? allSteps.length + 1,
            title: s.title ?? `Step ${allSteps.length + 1}`,
            description: s.description ?? "",
            imageUrl: img.data,
            annotations: Array.isArray(s.annotations) ? s.annotations : [],
            tip: s.tip || null,
          });
        }
      } catch {
        // Gemini returned malformed JSON — use fallback
        allSteps.push({
          step: allSteps.length + 1,
          title: `Step ${allSteps.length + 1}`,
          description: "Documentation generated by AI.",
          imageUrl: img.data,
          annotations: [],
          tip: null,
        });
      }
    }
  }

  return allSteps;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { images } = body as {
      images: Array<{ id: string; data: string; name: string }>;
    };

    if (!images || images.length === 0) {
      return NextResponse.json({ error: "No images provided." }, { status: 400 });
    }

    let steps: ReturnType<typeof generateWithGemini> extends Promise<infer T> ? T : never = [];
    let aiModel = "mock";

    try {
      steps = await generateWithGemini(images);
      aiModel = GEMINI_MODEL;
    } catch (err) {
      console.error("Gemini failed, using mock:", err);
      // Fallback mock data
      const mockTitles = [
        "Log in to your account",
        "Navigate to the dashboard",
        "Access settings",
        "Configure preferences",
        "Save and confirm",
      ];
      steps = images.map((img, idx) => ({
        step: idx + 1,
        title: mockTitles[idx % mockTitles.length],
        description: "AI-generated description. Configure your API key to get real results.",
        imageUrl: img.data,
        annotations: ["Button", "Form field", "Menu"],
        tip: "Tip: Sign up for free to access all features.",
      }));
    }

    // Save to Supabase if configured
    let docId: string | null = null;
    try {
      const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
      const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
      if (supabaseUrl && supabaseKey) {
        const { createClient } = await import("@supabase/supabase-js");
        const supabase = createClient(supabaseUrl, supabaseKey);
        const { data: docData } = await supabase
          .from("documents")
          .insert({
            title: `Doc ${new Date().toLocaleDateString()}`,
            status: "completed",
            steps_count: steps.length,
            export_format: "markdown",
          })
          .select("id")
          .single();

        if (docData?.id) {
          docId = docData.id;
          const stepRecords = steps.map((s, idx) => ({
            document_id: docId,
            step_number: s.step,
            title: s.title,
            description: s.description,
            image_url: s.imageUrl,
            annotations: s.annotations,
            tip: s.tip,
            order_index: idx,
          }));
          await supabase.from("document_steps").insert(stepRecords);
        }
      }
    } catch {
      // Supabase not configured — skip
    }

    return NextResponse.json({ steps, document_id: docId, ai_model: aiModel });
  } catch (error) {
    console.error("DocSnap API error:", error);
    return NextResponse.json(
      { error: "Failed to generate documentation. Please try again." },
      { status: 500 }
    );
  }
}
